### ISSUE TITLE
Alguns exemplos precisam de uma explicação mais elaborada

### ISSUE THREAD

**Issue by crgimenes** [go-br/estudos#24]
O material foi escrito inicialmente para ser usado em workshops e por esse motivo alguns dos exemplos não funcionam bem se não tiver alguém explicando. 

Precisamos elaborar melhor os textos para que eles funcionem para o leitor que não tem alguém a mão para explicar. 

Entretanto quando for incluir mais explicações tente preservar a dinâmica de experimentar e testar rapidamente. Evite textos grandes e complicados, vá direto ao ponto.

**Comment by cassiobotaro** [comment]
vi alguns repositórios como "draft", não seria mais legal deixar separado os rascunhos em um diretório `rascunho` separado? Seria massa pedir durante as reuniões de quinta contribuições com assuntos.

**Comment by crgimenes** [comment]
Boa ideia @cassiobotaro para as duas coisas :D
