### ISSUE TITLE
Renomear repositório

### ISSUE THREAD

**Issue by crgimenes** [go-br/estudos#29]
Quero renomear o repositório, principalmente remover os traços 
Go-Hands-On já não reflete tão bem a forma que material esta tomando.

Qual sua opinião? Sugestões de nomes?

**Comment by edwardmartinsjr** [comment]
we2go - ["Where Else Have We To Go"]

**Comment by cassiobotaro** [comment]
Acho que deveria ser algo em pt-br, refletindo que o material está português....
- gonapratica
- gomaonamassa
- gonapratica
- aprendendogoporexemplos

**Comment by luisvinicius167** [comment]
- goparahumanos
- goforhumans

**Comment by avelino** [comment]
- Learning Go #42

**Comment by crgimenes** [comment]
Esses dias ouvi um nome legal: "3 2 1 Go"
haha

**Comment by guiferpa** [comment]
learn-about-go

**Comment by crgimenes** [comment]
Criei a organização *go-br* e o repo principal é o *estudos*.
Obrigado a todos pelas sugestões!
