### ISSUE TITLE
Adicionar uma pagina para conter os editores e IDEs com suporte a Golang, do VIM ao Emacs :D

### ISSUE THREAD

**Issue by diegofsousa** [go-br/estudos#45]
Assim como o Atom e VSCode, existem no Sublime _plugins_ que auxiliam no desenvolvimento. É o caso do [GoSublime](https://github.com/DisposaBoy/GoSublime). O que vocês acham de adicionarmos logo após o Visual Studio Code?

**Comment by crgimenes** [comment]
Talvez seja interessante uma parte para editores e IDEs, dai colocamos tudo que o povo gosta, de VIM a Eclipse :D

**Comment by diegofsousa** [comment]
Farei um PR só adicionando o Sublime e você verifica se ficou legal, pode ser? A medida que fosse aparecendo mais ferramentas para desenvolvimento a seção poderia ser re-estruturada. :)

**Comment by crgimenes** [comment]
Ficou sim.
Mas ainda precisamos criar uma pagina especifica para editores / ides dai cobrimos tudo
