### ISSUE TITLE
Converte em uma estrutura Hugo 

### ISSUE THREAD

**Issue by avelino** [go-br/estudos#53]
Acho muito legal a ideia do repositório só peca por falta de melhor indexação no Google (atingir/ajudar mais pessoas).
Qual a opinião de você em converter (reestruturar) o conteúdo em um site Hugo?

**Comment by crgimenes** [comment]
Eu gosto da ideia! 
Acho fácil escrever um conversor que basicamente transforma tudo em artigos do HUGO.

**Comment by crgimenes** [comment]
Seguindo essa ideia registrei o domínio https://gopher.pro.br e criei um código que lê o repositório [estudos](https://github.com/go-br/estudos) e gera os artigos que depois um pequeno script bash usa o Hugo e converte para HTML e em seguida atualiza as chaves SSL se necessário.

Esse é o código que gera os posts do Hugo: https://github.com/go-br/sitegen
