### ISSUE TITLE
Usar sistema de labels nas issues

### ISSUE THREAD

**Issue by avelino** [go-br/estudos#54]
Pensando em atrair mais pessoas para contribuir com o repositório acho legal começarmos usar o sistema de labels para issues, assim conseguimos organizar as melhorias e contribuições.

Dado que o conteúdo desse repositório é em pt-br nada mais justo de manter as labels em pt-br 😄

**Comment by crgimenes** [comment]
Acho interessante, mas quero ouvir a opinião do pessoal.

Falando sobre ingles X português, colocamos as variáveis e alguns nomes de função em português depois que descobrimos que algumas pessoas que estavam iniciando confundiam muito facilmente variáveis com palavras reservadas. Eu me arrependi disso, no lugar acredito que devíamos ter deixado em ingles e talvez explicado o código com mais comentários ou nos videos e workshops.

Pessoal deixem suas opiniões por favor, @marioidival @jtemporal @felipeweb  @trumae @jg19 @zeucxb

**Comment by jg19** [comment]
Pessoalmente tenho muita dificuldade com inglês, mas acredito que as labels poderiam ficar em inglês sem problema. Talvez pudesse explicar o que é cada um no readme, em um local apropriado de fácil visualização. 
No caso de código, acredito que seja melhor ter os comentários em Português e o código em inglês.
Querendo ou não inglês é universal, e quando mais contato os novos (e experientes) programadores tiverem facilita sua vida no futuro.

**Comment by marioidival** [comment]
Concordo com o @avelino.

Sobre o ponto do @crgimenes, com a experiencia que estou adquirindo na tradução do livro de Rust, e vendo em outras traduções, o ideal seria traduzir nomes, funções, interfaces, tudo para pt-BR.

Minha opinião seria essa, conteúdo em ptBR, código ptBR.

**Comment by jtemporal** [comment]
Uma coisa que eu já vi fazer quanto as labels é por exemplo usar o nome em ingles/portugues tipo `question / pergunta`. Isso ajuda a pessoas a aprenderem as labels tradicionais e também não se perderem na tradução :)

Fora isso, sou muito a favor do código "traduzido" para pt-br. A minha xp com o Django Girls me mostra que ter isso ajuda muito o entendimento de pessoas que estão chegando para aprender a programar com a diminuição da barreira da língua.

**Comment by zeucxb** [comment]
Bem, eu costumo usar tudo em inglês, mas recentemente tenho ensinado alguns amigos que não tiveram contato algum com programação e inglês.

Talvez o inglês seja realmente uma barreira a mais que podemos remover, por outro lado, será qu essa dúvida (do significado da palavra) não estimula a pesquisa e ajuda no aprender a aprender?

**Comment by avelino** [comment]
Minha visão seria manter texto em EN e código (nome de var, functions e etc) em EN e comentários de código em pt-BR, mas nunca tive experiencia de ensinar programação para quem não sabe programar, lendo os comentários de vocês minha opinião mudou.

Dado que o material é em pt-BR acho justo tudo ficar pt-BR, obrigado por abrir meus olhos para esse ponto galera.

**Comment by jtemporal** [comment]
> não estimula a pesquisa e ajuda no aprender a aprender?

Depende, maior parte dos casos que vi, não estimula não... No DG minha experiência é que todas as barreiras que puderem ser removidas devem ser removidas e, por mais que desenvolvimento traga o inglês desde sempre, uma outra língua é uma barreira considerável :wink:

**Comment by zeucxb** [comment]
Entendo, 🤔

**Comment by jg19** [comment]
Já dei aula de programação por um bom tempo, eu gostava de usar e mostrar os termos originais e incentivar a usar inglês, pois não tem apenas a barreira inicial, tem que haver continuidade no aprendizado, principalmente estudando por conta, e a barreira sempre vai existir, e todo material e documentação oficial é em inglês.
Aprendi muito quando comecei a ler código e documentação  em inglês mesmo não tendo domínio da linguagem.
Não vejo como diminuir barreiras, e sim ensinar a transpassá-las, pois elas sempre vão existir querendo ou não.
